# Generated by Django 4.1.7 on 2023-03-04 12:56

import app_istam.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_istam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='foto',
            field=models.ImageField(blank=True, upload_to=app_istam.models.url),
        ),
        migrations.AlterField(
            model_name='carrera',
            name='tipo_carrera',
            field=models.CharField(choices=[('001', 'TECNOLOGICA'), ('002', 'ADMINISTRACION')], max_length=45),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='ciclo',
            field=models.CharField(max_length=10),
        ),
    ]
