# Generated by Django 4.1.7 on 2023-03-05 18:07

import app_istam.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_istam', '0002_estudiante_foto_alter_carrera_tipo_carrera_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matricula',
            name='genero',
        ),
        migrations.RemoveField(
            model_name='matricula',
            name='periodo_academico',
        ),
        migrations.AlterField(
            model_name='matricula',
            name='ciclo',
            field=models.CharField(choices=[('1', 'I CICLO'), ('2', 'II CICLO'), ('3', 'III CICLO'), ('4', 'IV CICLO'), ('5', 'V CICLO')], default='available', max_length=10),
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.IntegerField()),
                ('direccion', models.TextField()),
                ('cedula', models.CharField(max_length=10)),
                ('foto', models.ImageField(upload_to=app_istam.models.url_perfil)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfiles',
            },
        ),
    ]
