# Generated by Django 4.1.7 on 2023-03-05 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_istam', '0003_remove_matricula_genero_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
